# Dockerfile for generating the Nginx Docker image used as a reverse proxy
# for securing the ArchivesSpace API endpoint.
#
# To build:
#
# docker build -t docker.lib.umd.edu/aspace-api-proxy:<VERSION> -f Dockerfile-api-proxy .
#
# where <VERSION> is the Docker image version to create.
FROM nginx:1.19.2-alpine
COPY docker_config/api-proxy/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8082 8083
