# Dockerfile for the generating Apache Solr Docker image
# Based on the "archivesspace/solr/Dockerfile" for the given version,
# i.e.:
#
# https://github.com/archivesspace/archivesspace/blob/v4.1.1/solr/Dockerfile
#
# To build:
#
# docker build -t docker.lib.umd.edu/aspace-solr:<VERSION> -f Dockerfile-solr .
#
# where <VERSION> is the Docker image version to create.
FROM solr:9.4.1
LABEL maintainer="ArchivesSpaceHome@lyrasis.org"

ENV ARCHIVESSPACE_CONFIGSET_PATH=/opt/solr/server/solr/configsets/archivesspace/conf
ENV SOLR_MODULES=analysis-extras

USER root

RUN mkdir -p $ARCHIVESSPACE_CONFIGSET_PATH
COPY docker_config/solr/conf/* $ARCHIVESSPACE_CONFIGSET_PATH/
RUN chown -R solr:solr $ARCHIVESSPACE_CONFIGSET_PATH

# ASPACE REQUIRES THESE LIBS (WHICH ARE INCL. IN THE v9 IMG):
# /opt/solr/modules/analysis-extras/lib/solr-analysis-extras-*.jar
# /opt/solr/modules/analysis-extras/lib/lucene-analysis-icu-*.jar
# /opt/solr/modules/analysis-extras/lib/icu4j-*.jar

USER solr
