# Dockerfile for the generating Apache Solr Docker image
#
# To build:
#
# docker build -t docker.lib.umd.edu/aspace-solr:<VERSION> -f Dockerfile-solr .
#
# where <VERSION> is the Docker image version to create.

FROM solr:6.6.4-alpine

# Create Solr core for ArchivesSpace

ARG SOLR_DIR=/opt/solr
ENV SOLR_DIR=${SOLR_DIR}

RUN cp -r ${SOLR_DIR}/server/solr/configsets/basic_configs ${SOLR_DIR}/server/solr/configsets/archivesspace && \
    rm ${SOLR_DIR}/server/solr/configsets/archivesspace/conf/managed-schema

COPY docker_config/solr/conf/* ${SOLR_DIR}/server/solr/configsets/archivesspace/conf/

RUN ${SOLR_DIR}/bin/solr start && \
    ${SOLR_DIR}/bin/solr create -c archivesspace -d ${SOLR_DIR}/server/solr/configsets/archivesspace/conf/ &&\
    ${SOLR_DIR}/bin/solr stop

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["solr-foreground"]